name: ourvalley
favicon: null
layout_spectrum: 0.75039
typography_spectrum: 0.24961
title: Vakantiewoning Burg Reuland
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cc3f23'
    - '#d4eba4'
    - '#503f3c'
    - '#d8f1aa'
    - '#a6b083'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
