name: ourvalley
favicon: null
layout_spectrum: 0.86776
typography_spectrum: 0.24961
title: Vakantiewoning Burg Reuland
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050e0d'
    - '#ffffff'
    - '#68692f'
    - '#83984b'
    - '#c4b9b3'
  brandStrength: 0.5
  lightness: 0.25
  saturation: 0.125
  rhythmicContrast: 0.25
purpose: []
